source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'mysql2', '~> 0.2.6'
gem 'jquery-rails'
gem 'haml'
gem 'haml-rails'
gem 'formtastic'
gem 'paperclip', '~> 2.3'
gem 'fastercsv'
gem 'rake', '0.9.2'
gem 'best_in_place'